name: Babelfish for PostgreSQL Extensions Feature Request Form
description: Propose an enhancement for Babelfish for PostgreSQL Extensions
title: "[Enhancement]: "
labels: ["enhancement", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please provide an email address where we can contact you for more information.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-intends
    attributes:
      label: What is the issue this feature/enhancement tries to resolve?
      description: Provide as many details about the feature as possible.
      placeholder: Provide as many feature details as possible.
      value: "This is my feature request!"
    validations:
      required: true
  - type: textarea
    id: brief-desc-implementation
    attributes:
      label: Provide implementation details (if possible) for the feature.
      description: Share implementation details for the feature.
    validations:
      required: false 
  - type: textarea
    id: docs
    attributes:
      label: Relevant documentation.
      description: Please attach documentation relevant to the feature.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aws.github.io/code-of-conduct-faq).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true