name: JDBC Tests

on:
  workflow_call:

jobs:

  run-babelfish-jdbc-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout

      # - name: Download binaries
      #   id: download-binaries
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: binaries
      #     path: ./binaries.zip

      - name: Download binaries
        id: download-binaries
        # See https://github.com/marketplace/actions/download-workflow-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: base.yml
          name: binaries
          path: ~/postgres #./binaries.zip

      # - name: Unzip bins
      #   id: unzip-bins
      #   run: |
      #     unzip -d ~/postgres/ /home/runner/work/babelfish_extensions/babelfish_extensions/binaries.zip/binaries.zip

      - name: Install Extensions
        id: install-extensions
        if: always() && steps.unzip-bins.outcome == 'success'
        uses: ./.github/composite-actions/install-extensions

      - name: Run JDBC Tests
        id: jdbc
        #if: always() && steps.install-extensions.outcome == 'success'
        timeout-minutes: 15
        run: |
          cd test/JDBC/
          mvn test
      
      - name: Upload Log
        if: always() && steps.jdbc.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: postgres-log
          path: ~/postgres/data/logfile
      
      # The test summary files contain paths with ':' characters, which is not allowed with the upload-artifact actions
      - name: Rename Test Summary Files
        id: test-file-rename
        if: always() && steps.jdbc.outcome == 'failure'
        run: |
          cd test/JDBC/Info
          timestamp=`ls -Art | tail -n 1`
          cd $timestamp
          mv $timestamp.diff ../output-diff.diff
          mv "$timestamp"_runSummary.log ../run-summary.log
      
      - name: Upload Run Summary 
        if: always() && steps.test-file-rename == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: run-summary.log
          path: test/JDBC/Info/run-summary.log
      
      - name: Upload Output Diff
        if: always() && steps.jdbc.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: output-diff.diff
          path: test/JDBC/Info/output-diff.diff
