name: ODBC Tests

on:
  workflow_call:

jobs:

  run-babelfish-odbc-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - name: Download binaries
        id: download-binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Unzip bins
        id: unzip-bins
        run: |
          unzip -d ~/postgres/ binaries.zip

      - name: Install Extensions
        id: install-extensions
        if: always() && steps.unzip-bins.outcome == 'success'
        uses: ./.github/composite-actions/install-extensions

      - name: Install ODBC Driver
        id: install-odbc-driver
        if: always() && steps.install-extensions.outcome == 'success'
        run: |
          cd ~
          sudo apt-get install msodbcsql17
      
      - name: Run ODBC Tests
        if: always() && steps.install-odbc-driver.outcome == 'success'
        run: |
          cd test/odbc
          cmake -S . -B build
          cmake --build build
          BABEL_DB_SERVER=localhost \
            BABEL_DB_PORT=1433 \
            BABEL_DB_USER=jdbc_user \
            BABEL_DB_PASSWORD=12345678 \
            BABEL_DB_NAME=master \
            ./build/main
